Remove immediately calling anzii on require
Anzii is supposed to return a nodejs module on require instead of immediately calling anzii method. Immediately calling anzii was only needed in production. Require in production emitted a 'TypeError: require() is not a function'. With this commit, the intended behaviour has implemented.